name: learn-github-actions
on: [push]  # trigger event
jobs:
  check-bats-version:  # job id
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2  # use action
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: pip install -r requirements.txt  # run shell cmd
      - run: python -m unittest discover tests